# Generated by Django 4.1.7 on 2023-03-16 01:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_part_alter_suivrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_id', models.IntegerField(null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fipe_value', models.FloatField(null=True)),
                ('state', models.CharField(max_length=50)),
                ('value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('version_id', models.IntegerField(null=True)),
                ('kilometers', models.PositiveIntegerField(null=True)),
                ('months', models.PositiveIntegerField(null=True)),
                ('parcels', models.PositiveIntegerField(null=True)),
                ('duration_minutes', models.PositiveIntegerField(null=True)),
                ('full_price', models.FloatField(null=True)),
                ('parcel_price', models.FloatField(null=True)),
                ('changed_parts', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict), blank=True, default=list, null=True, size=None)),
                ('inspections', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSpecsVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(null=True)),
                ('fipe_id', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('specs', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_id', models.IntegerField(null=True)),
                ('version_id', models.IntegerField(null=True)),
                ('maker_description', models.CharField(max_length=255, null=True)),
                ('model_description', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255)),
                ('imageUrl', models.URLField()),
                ('makerLogoUrl', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='axis_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seat_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_fab',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_model',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='api.vehicle', verbose_name='Recalls')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
