# Generated by Django 4.1.7 on 2023-03-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipment_ipva_revisionplan_technicalspecsvehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_id', models.IntegerField(null=True)),
                ('version_id', models.IntegerField(null=True)),
                ('maker_description', models.CharField(max_length=255, null=True)),
                ('model_description', models.CharField(max_length=255, null=True)),
                ('text', models.TextField()),
                ('imageUrl', models.URLField()),
                ('makerLogoUrl', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleSummary',
        ),
    ]
