# Generated by Django 4.1.7 on 2023-03-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_summaryvehicle_delete_vehiclesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryvehicle',
            name='imageUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='summaryvehicle',
            name='makerLogoUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='summaryvehicle',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
