# Generated by Django 4.1.7 on 2023-03-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_summaryvehicle_imageurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryvehicle',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='summaryvehicle',
            old_name='makerLogoUrl',
            new_name='maker_logo_url',
        ),
    ]
