# Generated by Django 4.1.7 on 2023-03-16 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_imageurl_summaryvehicle_image_url_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='TechnicalSpecsGroup',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('plate', models.CharField(max_length=7, null=True)),
        #         ('fipe_id', models.IntegerField(null=True)),
        #         ('year', models.PositiveIntegerField(null=True)),
        #         ('description', models.CharField(max_length=255)),
        #         ('specs', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, null=True, size=None)),
        #     ],
        # ),
        migrations.RemoveField(
            model_name='comparisondata',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='TechnicalSpecsVehicle',
        ),
        migrations.DeleteModel(
            name='ComparisonData',
        ),
    ]
