# Generated by Django 4.1.7 on 2023-03-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_technicalspecsgroup_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_series',
            field=models.BooleanField(null=True),
        ),
    ]
